require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'MobileApp' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'TcpSockets', :path => '../node_modules/react-native-tcp'


  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'MobileAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MobileApp-tvOS' do
  # Pods for MobileApp-tvOS

  target 'MobileApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
