export const availableButtons = {
  a: {name: 'a / A', value: 'a'},
  b: {name: 'b / B', value: 'b'},
  c: {name: 'c / C', value: 'c'},
  d: {name: 'd / D', value: 'd'},
  e: {name: 'e / E', value: 'e'},
  f: {name: 'f / F', value: 'f'},
  g: {name: 'g / G', value: 'g'},
  h: {name: 'h / H', value: 'h'},
  i: {name: 'i / I', value: 'i'},
  j: {name: 'j / J', value: 'j'},
  k: {name: 'k / K', value: 'k'},
  l: {name: 'l / L', value: 'l'},
  m: {name: 'm / M', value: 'm'},
  n: {name: 'n / N', value: 'n'},
  o: {name: 'o / O', value: 'o'},
  p: {name: 'p / P', value: 'p'},
  q: {name: 'q / Q', value: 'q'},
  r: {name: 'r / R', value: 'r'},
  s: {name: 's / S', value: 's'},
  t: {name: 't / T', value: 't'},
  u: {name: 'u / U', value: 'u'},
  v: {name: 'v / V', value: 'v'},
  w: {name: 'w / W', value: 'w'},
  x: {name: 'x / X', value: 'x'},
  y: {name: 'y / Y', value: 'y'},
  z: {name: 'z / Z', value: 'z'},
  one: {name: '1', value: '1'},
  two: {name: '2', value: '2'},
  three: {name: '3', value: '3'},
  four: {name: '4', value: '4'},
  five: {name: '5', value: '5'},
  six: {name: '6', value: '6'},
  seven: {name: '7', value: '7'},
  eight: {name: '8', value: '8'},
  nine: {name: '9', value: '9'},
  zero: {name: '0', value: '0'},
  shift: {name: 'Left Shift', value: 'shift'},
  space: {name: 'Space', value: 'space'},
  rightShift: {name: 'Right Shift', value: 'right_shift'},
  alt: {name: 'Alt', value: 'alt'},
  ctrl: {name: 'Ctrl', value: 'control'},
  backspace: {name: 'Backspace', value: 'backspace'},
  enter: {name: 'Enter', value: 'enter'},
  tab: {name: 'Tab', value: 'tab'},
  esc: {name: 'Esc', value: 'escape'},
  home: {name: 'Home', value: 'home'},
  end: {name: 'End', value: 'end'},
  f1: {name: 'F1', value: 'f1'},
  f2: {name: 'F2', value: 'f2'},
  f3: {name: 'F3', value: 'f3'},
  f4: {name: 'F4', value: 'f4'},
  f5: {name: 'F5', value: 'f5'},
  f6: {name: 'F6', value: 'f6'},
  f7: {name: 'F7', value: 'f7'},
  f8: {name: 'F8', value: 'f8'},
  f9: {name: 'F9', value: 'f9'},
  f10: {name: 'F10', value: 'f10'},
  f11: {name: 'F11', value: 'f11'},
  f12: {name: 'F12', value: 'f12'},
  up: {name: 'Up Arrow', value: 'up'},
  down: {name: 'Down Arrow', value: 'down'},
  left: {name: 'Left Arrow', value: 'left'},
  right: {name: 'Right Arrow', value: 'right'},
  empty: {name: '', value: ''},
};

export const defaultButtons = {
  up: {button: 'Arrow Up', key: availableButtons.up},
  down: {button: 'Arrow Down', key: availableButtons.down},
  left: {button: 'Arrow Left', key: availableButtons.left},
  right: {button: 'Arrow Right', key: availableButtons.right},
  triangle: {button: 'Triangle', key: availableButtons.a},
  square: {button: 'Square', key: availableButtons.d},
  cross: {button: 'Cross', key: availableButtons.space},
  circle: {button: 'Circle', key: availableButtons.z},
  pause: {button: 'Pause', key: availableButtons.esc},
  start: {button: 'Start', key: availableButtons.enter},
  l: {button: 'Left(L)', key: availableButtons.rightShift},
  r: {button: 'Right(R)', key: availableButtons.shift},
  e1: {button: 'Extra 1', key: availableButtons.empty},
  e2: {button: 'Extra 2', key: availableButtons.empty},
  e3: {button: 'Extra 3', key: availableButtons.empty},
  e4: {button: 'Extra 4', key: availableButtons.empty},
};

export const orderedButtons = [
  'triangle',
  'square',
  'cross',
  'circle',
  'up',
  'down',
  'left',
  'right',
  'pause',
  'start',
  'l',
  'r',
  'e1',
  'e2',
  'e3',
  'e4',
];
